<?xml version="1.0" encoding="utf-8"?><Database Name="CounselorBOT" Class="DBTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=217.20.112.152;Initial Catalog=CounselorBOT;Persist Security Info=True;User ID=CounselorBot" SettingsObjectName="KetabKhan.Properties.Settings" SettingsPropertyName="CounselorBOTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Test" Member="Tests">
    <Type Name="Test">
      <Column Name="Message" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>