<?xml version="1.0" encoding="utf-8"?><Database Name="DBLab" Class="DBTest1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-T590RA7\SQLEXPRESS;Initial Catalog=DBLab;Integrated Security=True" SettingsObjectName="KetabKhan.Properties.Settings" SettingsPropertyName="DBLabConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Exam" Member="Exams">
    <Type Name="Exam">
      <Column Name="ExamID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExamName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Exam_ExamQuestion" Member="ExamQuestions" ThisKey="ExamID" OtherKey="ExamID" Type="ExamQuestion" />
    </Type>
  </Table>
  <Table Name="dbo.ExamChoices" Member="ExamChoices">
    <Type Name="ExamChoice">
      <Column Name="ChoiceID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Choice" Type="System.String" DbType="NChar(1000)" CanBeNull="true" />
      <Column Name="RightAnswer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="QuestionID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="ExamQuestion_ExamChoice" Member="ExamQuestion" ThisKey="QuestionID" OtherKey="QuestionID" Type="ExamQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExamQuestion" Member="ExamQuestions">
    <Type Name="ExamQuestion">
      <Column Name="QuestionID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExamID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="NChar(1000)" CanBeNull="true" />
      <Column Name="RightAnswer" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Association Name="ExamQuestion_ExamChoice" Member="ExamChoices" ThisKey="QuestionID" OtherKey="QuestionID" Type="ExamChoice" />
      <Association Name="Exam_ExamQuestion" Member="Exam" ThisKey="ExamID" OtherKey="ExamID" Type="Exam" IsForeignKey="true" />
    </Type>
  </Table>
</Database>